name: Build Minecraft Server Query Command

on:
  push:
    branches: [ master ]
    paths: [ 'minecraft_server_query/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'minecraft_server_query/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Projects"
      uses: actions/checkout@v2
    
    - name: "Setup PHP"
      uses: shivammathur/setup-php@2.1.3

    - name: "Install Build Dependencies"
      run: composer install
  
    - name: "Install Build Target Dependencies"
      run: composer install
      working-directory: "./minecraft_server_query"
    
    - name: "Build Target"
      run: composer build
      working-directory: "./minecraft_server_query"

    - name: "Zip Build"
      run: zip minecraft_server_query.phar.zip minecraft_server_query.phar
      working-directory: "/bin"

    - name: Push to CDN
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${{ secrets.CDN_INGRESS_KEY }}"
        scp -o StrictHostKeyChecking=no -v -P "${{ secrets.CDN_INGRESS_PORT }}" -r bin/minecraft_server_query.phar.zip "${{ secrets.CDN_INGRESS_USER }}"@"${{ secrets.CDN_INGRESS }}":"${{ secrets.CDN_PATH }}"
